services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.prairie.ovh
    networks:
      - smart-home-net
      - immich-net
      - jellyfin-net
    labels:
      glance.name: Newt
      glance.parent: vpn

networks:
  jellyfin-net:
    external: true
  immich-net:
    external: true
  smart-home-net:
    external: true
