---
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /opt/docker-data/komga
        target: /config
      - type: bind
        source: /mnt/zfs/lamapound
        target: /data
      - type: bind
        source: /etc/timezone #alternatively you can use a TZ environment variable, like TZ=Europe/London
        target: /etc/timezone
        read_only: true
    # ports:
    #   - 25600:25600
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    # environment:
    #   - <ENV_VAR>=<extra configuration>
    restart: unless-stopped
    networks:
      - komga-net
    labels:
      glance.name: Komga
      glance.icon: sh:komga
      glance.url: https://komga.lan.prairie.ovh
      glance.description: Webtoon Reader
      glance.category: media

networks:
  komga-net:
    external: true
