---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Paris
    volumes:
      - /mnt/zfs/lamapound:/mnt/zfs/lamapound #optional
      - /mnt/sshfs/ultra:/home/blamo12
      - /opt/docker-data/radarr:/config
    # ports:
    #   - 7878:7878
    restart: unless-stopped
    networks:
      - arr-net
      - auth-net
    labels:
      glance.name: Radarr
      glance.icon: si:radarr
      glance.url: https://radarr.lan.prairie.ovh
      glance.description: Movies metadata
      glance.id: radarr

networks:
  arr-net:
    external: "true"
  auth-net:
    external: "true"
