services:
  postgresql:
    env_file:
    - secrets.postgres.enc.env
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
    - pg_database:/var/lib/postgresql/data

  authentik-server:
    command: server
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
    - secrets.authentik.enc.env
    - secrets.postgres.enc.env
    - env-authentik
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.10.1}
    # ports:
    # - ${COMPOSE_PORT_HTTP:-9000}:9000
    # - ${COMPOSE_PORT_HTTPS:-9443}:9443
    restart: unless-stopped
    networks:
      - auth-net
      - default
    volumes:
    - /opt/docker-data/authentik/media:/media
    - /opt/docker-data/authentik/custom-templates:/templates

  authentik-worker:
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - secrets.authentik.enc.env
      - secrets.postgres.enc.env
      - env-authentik
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.10.1}
    restart: unless-stopped
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/docker-data/authentik/media:/media
    - /opt/docker-data/authentik/certs:/certs
    - /opt/docker-data/authentik/custom-templates:/templates

  # authentik-ldap:
  #       image: ${AUTHENTIK_OUTPUT_LDAP_IMAGE:-ghcr.io/goauthentik/ldap}:${AUTHENTIK_TAG:-2025.10.1}
  #       # Optionally specify the container's network, which must be able to reach the core authentik server.
  #       # networks:
  #       #   - foo
  #       # ports:
  #       #     - 389:3389
  #       #     - 636:6636
  #       networks:
  #         - auth-net
  #       env_file:
  #           - secrets.ldap.enc.env
  #           - env-ldap
            
            

volumes:
  pg_database:
    driver: local

networks:
  default:
  auth-net:
    external: true
