name: affine
services:
  affine:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_server
    networks:
      - affine-net
      - default
    # ports:
    #   - '${PORT:-3010}:3010'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - /opt/docker-data/affine/uploads:/root/.affine/storage
      - /opt/docker-data/affine/config:/root/.affine/config
    env_file:
      - affine.env
      - secrets.postgres.enc.env
    restart: unless-stopped

  affine_migration:
    networks:
      - default
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - /opt/docker-data/affine/uploads:/root/.affine/storage
      - /opt/docker-data/affine/config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    env_file:
      - affine.env
      - secrets.postgres.enc.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    container_name: affine_redis
    networks:
      - default
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres
    volumes:
      - /opt/docker-data/affine/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        test: ["CMD-SHELL", "pg_isready", "-U", "$$POSTGRES_USER", "-d", "$${POSTGRES_DB:-affine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  affine-net:
    external: true
  default: