services:
  stump:
    image: aaronleopold/stump:latest
    container_name: stump
    # Replace my paths (prior to the colons) with your own
    volumes:
      - ./config:/config
      - /mnt/zfs/lamapound:/mnt/zfs/lamapound
    # ports:
    #   - 10801:10801
    environment:
      - PUID=1000
      - PGID=1000
      # This `environment` field is optional, remove if you don't need it.
      # I am using it as an example here, but it's actually a default value.
      - STUMP_CONFIG_DIR=/config
    restart: unless-stopped
    networks:
      - komga-net

networks:
  komga-net:
    external: true
