services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker-data/frigate:/config
      - /mnt/zfs/lamapound/medias/videos/recording:/media/frigate/recordings
      - ./config/config.yaml:/config/config.yaml
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      #- "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    env_file:
      - frigate.env
      - secrets.frigate.enc.env
    networks:
      - smart-home-net
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              capabilities: [gpu]
    labels:
      glance.name: Frigate
      glance.icon: si:frigate
      glance.description: Network Video Recording
      glance.url: https://frigate.lan.prairie.ovh
      glance.id: frigate

networks:
  smart-home-net:
    external: true
