services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 8080:8080
    networks:
      - glance
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.glance.rule=Host(`glance.iot.jusma.fr`)"
    #   - "traefik.http.routers.glance.entrypoints=websecure"
    #   - "traefik.http.routers.glance.tls=true"
    #   - "traefik.http.routers.glance.tls.certresolver=letsencrypt"
    #   - "traefik.http.services.glance.loadbalancer.server.port=8080"
    labels:
      glance.name: Glance
      glance.icon: sh:glance
      glance.description: Dashboard
      glance.url: https://glance.lan.prairie.ovh

networks:
  glance-net:
    external: true
